test_grs: test/test_getRelativeSignals.cpp src/getRelativeSignals.cpp
	g++ test/test_getRelativeSignals.cpp src/getRelativeSignals.cpp -o test/getRelativeSignals

clean:
	rm -f *.o test/getRelativeSignals
